name: fastapi-ci

on:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - 
        name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - 
        name: Install pipenv
        run: pip install pipenv
      - 
        name: Run tests
        working-directory: ./fastapi
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          USER_BUCKET_NAME: ${{ secrets.USER_BUCKET_NAME }}
        run: |
          pipenv install -r requirements.txt
          pipenv run pytest -v
        

        
      -   
        name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - 
        name: Push data docs to S3 and enable static website hosting
        run: |
          aws s3 sync great_expectations_new/great_expectations/uncommitted/data_docs/local_site s3://damg-test --delete
          aws s3 website s3://damg-test --index-document index.html
        

